name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Run tests
        run: |
          python -m unittest discover
